services:
  permissionservice:
    image: permissionservice:latest
    container_name: permission_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - permissionservice
    networks:
      - backend

networks:
  backend:
    driver: bridge
