@Api_HostAddress = http://localhost:5113

POST {{Api_HostAddress}}/api/account
Content-Type: application/json
Accept: application/json

{
  "name": "string",
  "email": "user@example.com",
  "password": "string",
  "username": "string"
}

###
